server:
  port: 8080 # ?? ?? ????

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update        # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  #jOOQ Configuration
  jooq:
    sql-dialect: mysql

jwt:
  secret: 71b2def514eb60cc80e5b701aa5c6de66c33e9699e9a7f615a6a9998ae190c3db5a985081c8a150cf1d9b7fa9f32aa9bfcb568d9eda911c88274ead183ddb15e

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: debug