server:
  port: 8080 # ?? ?? ????

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update        # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  #jOOQ Configuration
  jooq:
    sql-dialect: mysql

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: debug